### ISSUE TITLE
program crashing on blank input when prompted for chapter selection

### ISSUE THREAD

**Issue by RawatDevanshu** [christianfds/manga_downloader#9]
```
Download this manga? Y/N  Y
1 - Chapter #1
Which indexes to download?
```

on hitting enter without typing anything the program crashes with following error:

```
Traceback (most recent call last):
  File "manga_downloader/manga_downloader.py", line 118, in <module>
    manga_downloader(args)
  File "manga_downloader/manga_downloader.py", line 85, in manga_downloader
    selected_chapters, chapters = select_chapters(provider, manga)
  File "manga_downloader/manga_downloader.py", line 61, in select_chapters
    selected_chapters = parse_chapter_selection(response)
  File "manga_downloader/manga_downloader.py", line 29, in parse_chapter_selection
    chapters = chapters + [int(section_range[0])]
ValueError: invalid literal for int() with base 10: ''
```

**Comment by Karthik-PM** [comment]
assign me this issue

**Comment by Alig1493** [comment]
@christianfds hope you don't mind the pr due to the inactivity. it'll probably be easier to handle with tests. I can add some coverage for it if needed.

**Comment by Karthik-PM** [comment]
yes thanks

**Comment by christianfds** [comment]
If you both ok with it. Thank you all.

@Alig1493 it would be nice to have some tests, if you want to do it I would really appreciate it. Just open an issue and i can assign it to you

**Comment by Alig1493** [comment]
@christianfds looks like there are no issues. I added some test in my PR for parsing chapter selection validation. Also it would be ideal if you could define the expected behaviour when the parse selections encounter blank, empty or strings containing only whitespaces.
